### ISSUE TITLE
Could not get unknown property 'generatedSourcesDir'

### ISSUE THREAD

**Issue by lucgirardin** [ascendtech/gwt-gradle#2]
I gave a quick try at using your plugin for one of my project. I get the following exception when running the gwtCompile task:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'generatedSourcesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getProperty(Unknown Source)
        at us.ascendtech.gwt.common.GWTBaseTask.exec(GWTBaseTask.groovy:42)
```
Is it because you are expecting that some kind of annotation processor is used?

**Comment by mdavis95** [comment]
I see. Yeah I believe we have always used an annotation processor.  I can make a change to not force it.

**Comment by lucgirardin** [comment]
That would be great: I could continue testing right away then ;-)

**Comment by mdavis95** [comment]
Can you give version 0.4.11 a try?

**Comment by lucgirardin** [comment]
Many thanks for changing this so rapidly: the issue is resolved and my multi-modules project do compile. I did spot a couple of smaller problems, but will report them as separate issues.
